server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userService
    username: root1
    password: root1
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect